{{ $NAMESPACE := .Release.Namespace }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "seed.fullname" . }}
  namespace: {{ $NAMESPACE }}
  labels:
    {{- include "seed.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "seed.selectorLabels" . | nindent 4 }}
