version: '2'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: semaphore
      POSTGRES_PASSWORD: semaphore
      POSTGRES_DB: semaphore
    ports:
      - "5432:5432"

  semaphore_ci:
    image: semaphoreui/semaphore:ci-compose
    build:
      context: ./../../../
      dockerfile: ./deployment/docker/ci/Dockerfile
    environment:
      SEMAPHORE_DB_DIALECT: postgres
      SEMAPHORE_DB_USER: semaphore
      SEMAPHORE_DB_PASS: semaphore
      SEMAPHORE_DB_HOST: postgres
      SEMAPHORE_DB_PORT: 5432
      SEMAPHORE_DB: semaphore
      SEMAPHORE_ADMIN_PASSWORD: password
      SEMAPHORE_ADMIN_NAME: "Developer"
      SEMAPHORE_ADMIN_EMAIL: admin@localhost
      SEMAPHORE_ADMIN: admin
      SEMAPHORE_WEB_ROOT: http://0.0.0.0:3000
      SEMAPHORE_ACCESS_KEY_ENCRYPTION: "IlRqgrrO5Gp27MlWakDX1xVrPv4jhoUx+ARY+qGyDxQ="
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  dredd:
    image: ansiblesemaphore/dredd:ci
    command: ["--config", ".dredd/dredd.yml"]
    environment:
      SEMAPHORE_ACCESS_KEY_ENCRYPTION: "IlRqgrrO5Gp27MlWakDX1xVrPv4jhoUx+ARY+qGyDxQ="
      SEMAPHORE_DB_DIALECT: postgres
    build:
      context: ./../../../
      dockerfile: ./deployment/docker/ci/dredd.Dockerfile
    depends_on:
      - semaphore_ci
      - postgres

