{{- $namespace := .Release.Namespace }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "global-secret"
  namespace: {{ $namespace}}
type: Opaque
data:
  DB_PASSWORD: {{ printf "%s" .Values.global.auth.postgres.password | b64enc | quote }}
  CLIENT_SECRET: {{ printf "%s" "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" | b64enc | quote }}
  